### ISSUE TITLE
Enable running isort on-save in vscode

### ISSUE THREAD

**Issue by fujikosu** [xinsnake/datascience-e2e#5]
Currently isort only runs when you run the command on vscode. This is the official document about how to run it https://code.visualstudio.com/docs/python/editing#_sort-imports

But to achieve the same quality of imports definition across the development team, enabling running isort on save would be helpful. This blob post seems helpful about how to set it up on vscode.
https://code.visualstudio.com/docs/python/editing#_sort-imports

This can be worked on after #4 is merged

**Comment by xinsnake** [comment]
This has now being configured following the guide here: https://copdips.com/2020/04/making-isort-compatible-with-black.html
